// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlipvfbyrioygeyjsiyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsaXB2ZmJ5cmlveWdleWpzaXlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTY1NDksImV4cCI6MjA2MjM5MjU0OX0.68CyUd4YGj9Lu34lZkbVo4TaRe6gKQ_7lCUvLHkYpSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);